name: Code Review

on:
  push:
    branches: [ dev ]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
   
      - name: Run npm Audit
        run: npm run audit
        continue-on-error: true

      - name: Run Snyk Scan and Save Report
        run: |
          npx snyk test --severity-threshold=low | tee snyk-report.txt
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Upload Snyk Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.txt
